import { z } from 'zod';

export const schema = z.object({
  peso:           z.number({ error: 'Requerido' }).positive(),
  estatura:       z.number({ error: 'Requerido' }).positive(),
  cintura:        z.number({ error: 'Requerido' }).positive(),
  fc:             z.number({ error: 'Requerido' }).positive(),
  glucosa:        z.number({ error: 'Requerido' }).positive(),
  ph_salival:     z.number({ error: 'Requerido' }).positive(),
  temp:           z.number({ error: 'Requerido' }).positive(),
  sexo:           z.enum(['M', 'F'], { error: 'Requerido' }),
  fitzpatrick:    z.number({ error: 'Requerido' }).min(1).max(6),
  p_4_1:          z.number({ error: 'Requerido' }).min(1).max(7),
  p_6_7:          z.number({ error: 'Requerido' }).min(1).max(5),
  p_6_2:          z.number({ error: 'Requerido' }).min(1).max(4),
  p_5_1:          z.number({ error: 'Requerido' }).min(1).max(3),
  carga_sintomas: z.number({ error: 'Requerido' }).min(0).max(5),
  p_2_1:          z.number({ error: 'Requerido' }).min(0).max(3),
  p_2_4:          z.number({ error: 'Requerido' }).min(0).max(3),
  p_6_10:         z.number({ error: 'Requerido' }).min(0).max(3),
  p_3_1:          z.number({ error: 'Requerido' }).min(0).max(3),
  p_3_8:          z.number({ error: 'Requerido' }).min(0).max(3),
  p_3_6:          z.number({ error: 'Requerido' }).min(0).max(3),
  p_3_5:          z.number({ error: 'Requerido' }).min(0).max(3),
  p_3_12:         z.number({ error: 'Requerido' }).min(0).max(3),
  p_4_2:          z.number({ error: 'Requerido' }).min(0).max(3),
  p_6_13:         z.number({ error: 'Requerido' }).min(0).max(3),
  p_1_3:          z.union([z.literal(0), z.literal(1)], { error: 'Requerido' }),
  p_6_3:          z.union([z.literal(0), z.literal(1)], { error: 'Requerido' }),
  p_6_5:          z.union([z.literal(0), z.literal(1)], { error: 'Requerido' }),
  p_5_4:          z.union([z.literal(0), z.literal(1)], { error: 'Requerido' }),
  p_5_3:          z.union([z.literal(0), z.literal(1)], { error: 'Requerido' }),
  p_5_7:          z.union([z.literal(0), z.literal(1)], { error: 'Requerido' }),
});